services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=Password!"
    ports:
      - "1433:1433"
    hostname: mssql
    volumes:
      - ./production/scripts:/var/opt/mssql/scripts
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    command: |
      sh -c "sleep 40 && /opt/mssql-tools/bin/sqlcmd -S mssql -U SA -P Password! -d master -i /var/opt/mssql/scripts/initBase.sql "
    stdin_open: true
    volumes:
      - ./sqlserver:/var/opt/mssql/scripts
    depends_on:
      - sqlserver